<?php
/**
 * Jamroom 5 jrProfile module
 *
 * copyright 2003 - 2013 by The Jamroom Network - All Rights Reserved
 * http://www.jamroom.net
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by The Jamroom
 * Network and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license than the Jamroom
 * Core - please reference the individual module or skin license that
 * is included with your download.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION!
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Unable to switch active profiles - you do not appear to have access to the requested profile';
$lang[2]  = 'Profile';
$lang[3]  = 'save settings';
$lang[4]  = 'active profile';
$lang[5]  = 'profile URL name';
$lang[6]  = 'profile image';
$lang[7]  = 'create new profile';
$lang[8]  = 'create';
$lang[9]  = 'profile name';
$lang[10] = 'Enter the name for the profile.';
$lang[11] = 'profile privacy';
$lang[12] = 'What level of privacy would you like to have for your Profile?';
$lang[13] = 'Global - anyone can view your profile';
$lang[14] = 'Private - only you can see your profile';
$lang[15] = 'Shared - only you and your followers can see your profile';
$lang[16] = 'This profile is a private profile and cannot be viewed';
$lang[17] = 'This is the URL name for your profile, which allows your profile to be accessed at the following URL:';
$lang[18] = 'The Profile Name you entered is already being used by another profile - please try another.';
$lang[19] = 'There is already another profile using that name - please select another.';
$lang[20] = 'The Profile Name you have entered is not allowed - please try another';
$lang[21] = 'profile biography';
$lang[22] = 'Enter a biography for this profile';
$lang[23] = 'Upload an image for your profile - this image will only be seen on your profile, and is separate from the image associated with your User Account.';
$lang[24] = 'This profile is private, and is only visible to followers.';
$lang[25] = 'Your Profiles';
$lang[26] = 'Profiles';
$lang[27] = 'Your profile has exceeded the allowed disk space for media items - modify or delete items to free up some space.';
